import mongoose from "mongoose";

const recRegisterSchema = new mongoose.Schema({
  ID_Rec: { type: String },
  rec_Date: { type: Date },
  ID_Emp: { type: String },
  ID_Position: { type: String },
  recID_Card: { type: String },
  recPrefix: { type: String },
  recFirst_Name_TH: { type: String },
  recLast_Name_TH: { type: String },
  recFirst_Name_EN: { type: String },
  recLast_Name_EN: { type: String },
  recNick_Name: { type: String },
  recDate_of_Birth: { type: Date },
  recAge: { type: Number },
  recGender: { type: String },
  recWeight: { type: Number },
  recHeight: { type: Number },
  recRace: { type: String },
  recNationality: { type: String },
  recReligion: { type: String },
  recPhysical_Ipairment: { type: String },
  recPhysical_Ipairment_other: { type: String },
  recCongenital_Dseases: { type: String },
  recCongenital_Dseases_other: { type: String },
  recCriminal_Record: { type: String },  // แก้ไขการสะกด
  recCriminal_Rcord_other: { type: String },
  recTattoo: { type: String },
  recTattoo_other: { type: String },
  recMotorcycle: { type: String },
  recMotorcycleLicense: { type: String },
  recCar: { type: String },
  recCarLicense: { type: String },
  fileInputRef: { type: String },
  recEducation:{ type: String },
  recWorkHistory:{ type: String },
  recWorkExperience: { type: String },
  recTel: { type: String },
  recEmail: { type: String },
  recLine: { type: String },
  recFacebook: { type: String },
  recProvice: { type: String },
  recDistrict: { type: String },
  recSubDistrict: { type: String, required: true },
  recPostcode: { type: String, required: true },
  recAddrees1: { type: String, required: true },
  recInterview1: { type: Boolean, default: false },
  recInterview2: { type: Boolean, default: false },
  ID_Req: { type: String },
  recWSD: { type: Date },
  recED: { type: Date },
  recActuality: { type: Boolean, default: false },
  proSignature: { type: String },
  ID_Payroll: { type: String },
});

const recRegister =
  mongoose.models.recRegister ||
  mongoose.model("recRegister", recRegisterSchema, "recRegister");

export default recRegister;
